### ISSUE TITLE
Slows down app significantly

### ISSUE THREAD

**Issue by NicoleMeganMoore** [makinacorpus/Leaflet.AlmostOver#10]
I love this feature, but when I use it, my app is significantly slower. There is a lot of latency when panning and zooming. Is there something I can do to speed it up? 

Edit: I only need it for click events, not hover. I increased the sampling period to 1 second and it is much much better.

**Comment by leplatrem** [comment]
If you only need click, then it would be relevant to add an option to disable mouse move events tracking!

You could add an option to this list (eg. `disableMouseMove` or something intuitive):
https://github.com/makinacorpus/Leaflet.AlmostOver/blob/gh-pages/src/leaflet.almostover.js#L10-L13

And skip listening of event when option is set:
https://github.com/makinacorpus/Leaflet.AlmostOver/blob/gh-pages/src/leaflet.almostover.js#L38-L39

What do you think?

**Comment by fpuga** [comment]
I'm also interested in this one, but i don't know [how to pass options the handler](https://stackoverflow.com/questions/41042071/how-do-i-pass-options-in-to-a-handler-in-leaflet-js).
