### ISSUE TITLE
L.Mixin.Events Deprecated

### ISSUE THREAD

**Issue by NicoleMeganMoore** [makinacorpus/Leaflet.AlmostOver#11]
Please change L.Mixin.Events to L.Evented as L.Mixin.Events will be removed from future versions.

**Comment by leplatrem** [comment]
Thanks for reporting this!

Don't hesitate to open a pull-request with the changes, we'd be happy to review or guide you through if needed :)

**Comment by cedricseyve** [comment]
I see this change was applied to the github repo.
NPM seems to contain a version without this change, could it be possible to update it aswell?

Would be very much appreciated !
And thanks for the nice plugin.

**Comment by leplatrem** [comment]
Done :) 1.0.1 published
