### ISSUE TITLE
Plugin does not work with Leaflet 1.3.1

### ISSUE THREAD

**Issue by AndreaAstronaut** [makinacorpus/Leaflet.AlmostOver#14]
Hi there,

the following code snippet works fine when using leaflet-src.js version 1.0.2 but not  using the newest leaflet version 1.3.1:
```
map.almostOver.addLayer(myPolyline]);

map.on('almost:over', function (e) {
                console.log('almost over line');
        });
```

With the new version I do not get any console.log statement when the mouse goes over the line.

Changing to the old leaflet file with no other changes it works perfect.

Any idea what is going wrong?

Thanks for your help,

Andrea

**Comment by bocall** [comment]
+1

I'm experiencing the same issue. Any info that could help would be gratefully appreciated.

**Comment by Elto505** [comment]
I also encountered this issue. hopefully it can be sorted

**Comment by tmyler** [comment]
+1

I am experiencing this issue as well. Has there been any investigation into it?

**Comment by leplatrem** [comment]
> Has there been any investigation into it?

I don't think so, please open a pull-request with the required changes!

**Comment by leplatrem** [comment]
Done :) 1.0.1 published

**Comment by AndreaAstronaut** [comment]
just tried it there and no change. last commit does not look like ti is there?

**Comment by vriens1988** [comment]
Here also not working see the plugin on the map, but nothing happen.

**Comment by leplatrem** [comment]
1.0.1 includes the event fix. What error do you have in the console?

https://github.com/makinacorpus/Leaflet.AlmostOver/commits/gh-pages

**Comment by AndreaAstronaut** [comment]
This issue is not about event. The functionality of AlmostOver is broken since Leaflet 1.3.1, see my initial post above.

**Comment by leplatrem** [comment]
You'd have to investigate yourself unfortunately, because I personally don't use this project anymore (nor work for this company)

I still have merge/release perms, so I still can merge and release a fix :)
